baseurl = "https://www.ribbybibby.me/"
languageCode = "en"
theme = "zozo"
paginate = 5
enableEmoji = true
summaryLength = 50 

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

title = "ROB BEST"

[[menu.main]]
  name = "Home"
  weight = 10
  url = "/"
[[menu.main]]
  name = "About"
  weight = 20
  identifier = "about"
  url = "/about"

[social]
  github = "https://github.com/ribbybibby"
  linkedin = "https://www.linkedin.com/in/ribbybibby/"

[params]
  enableSummary = true
